![Growdev](https://www.growdev.com.br/assets/images/logo_growdev.png)

# Tópicos da Aula de Hoje

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Pandas_logo.svg/2560px-Pandas_logo.svg.png" width="500" height="200" />

- Introdução ao Pandas
- Series

**Bora pra aula?**

In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.23.2 in c:\users\ferna\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ferna\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\ferna\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp311-cp311-win_amd64.whl (11.6 MB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/11.6 MB 7.0 MB/s eta 0:00:02
    --------------------------------------- 0.2/11.6 MB 2.5 MB/s eta 0:00:05
   - -------------------------------------- 0.6/11.6 MB 5.0 MB/s eta 0:00:03
   --- ------------------------------------ 0.9/11.6 MB 5.4 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/11.6 MB 6.4 MB/s eta 0:00:02
   ----- ---------------------------------- 1.6/11.6 MB 6.5 MB/s eta 0:00:02
   ------ --------------------------------- 1.9/11.6 MB 6.9 MB/s eta 0:00:02
   -------- ------------------------------- 2.4/11.6 MB 6.8 MB/s eta 0:00:02
   --------- ------------------------------ 2.6/11.6 MB 6.7 MB/s eta 0:00:02
   ---------- ----------------------------- 3.0/11.6 MB 6.9 MB/s eta 0:00:02
   ----------- ---------------------------- 3.4/11.6 MB 6.8 MB/s eta 0:00:02
   ------------ --------------------------- 3.7/11.6 MB 6.8 MB/s eta 0:00:02
   ------------- -------------------------- 4.0/11.6 MB 6.8 MB/s eta 0:00:02
   -------------- ------------------------- 4.3/11.6 MB 7.0 MB/s eta 0:00:02
   --------------- ------------------------ 4.4/11.6 MB 6.5 MB/s eta 0:00:02
   --------------- ------------------------ 4.6/11.6 MB 6.4 MB/s eta 0:00:02
   ---------------- ----------------------- 4.8/11.6 MB 6.2 MB/s eta 0:00:02
   ---------------- ----------------------- 4.9/11.6 MB 6.2 MB/s eta 0:00:02
   ----------------- ---------------------- 5.1/11.6 MB 6.0 MB/s eta 0:00:02
   ------------------ --------------------- 5.3/11.6 MB 5.9 MB/s eta 0:00:02
   ------------------- -------------------- 5.5/11.6 MB 5.8 MB/s eta 0:00:02
   ------------------- -------------------- 5.7/11.6 MB 5.6 MB/s eta 0:00:02
   -------------------- ------------------- 6.0/11.6 MB 5.7 MB/s eta 0:00:01
   --------------------- ------------------ 6.2/11.6 MB 5.7 MB/s eta 0:00:01
   ---------------------- ----------------- 6.5/11.6 MB 5.8 MB/s eta 0:00:01
   ----------------------- ---------------- 6.8/11.6 MB 5.7 MB/s eta 0:00:01
   ------------------------ --------------- 7.1/11.6 MB 5.7 MB/s eta 0:00:01
   ------------------------- -------------- 7.3/11.6 MB 5.6 MB/s eta 0:00:01
   -------------------------- ------------- 7.6/11.6 MB 5.6 MB/s eta 0:00:01
   --------------------------- ------------ 7.9/11.6 MB 5.7 MB/s eta 0:00:01
   ---------------------------- ----------- 8.1/11.6 MB 5.7 MB/s eta 0:00:01
   ----------------------------- ---------- 8.6/11.6 MB 5.8 MB/s eta 0:00:01
   ------------------------------ --------- 8.8/11.6 MB 5.9 MB/s eta 0:00:01
   ------------------------------- -------- 9.2/11.6 MB 5.9 MB/s eta 0:00:01
   -------------------------------- ------- 9.5/11.6 MB 5.9 MB/s eta 0:00:01
   --------------------------------- ------ 9.8/11.6 MB 5.8 MB/s eta 0:00:01
   --------------------------------- ------ 9.8/11.6 MB 5.8 MB/s eta 0:00:01
   ---------------------------------- ----- 10.1/11.6 MB 5.7 MB/s eta 0:00:01
   ----------------------------------- ---- 10.3/11.6 MB 5.7 MB/s eta 0:00:01
   ------------------------------------ --- 10.5/11.6 MB 5.8 MB/s eta 0:00:01
   ------------------------------------- -- 10.8/11.6 MB 5.7 MB/s eta 0:00:01
   -------------------------------------- - 11.2/11.6 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.6 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  11.6/11.6 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 11.6/11.6 MB 5.5 MB/s eta 0:00:00
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
   ---------------------------------------- 0.0/508.0 kB ? eta -:--:--
   ------------ --------------------------- 153.6/508.0 kB 4.6 MB/s eta 0:00:01
   --------------------- ------------------ 276.5/508.0 kB 4.3 MB/s eta 0:00:01
   ------------------------------------- -- 481.3/508.0 kB 3.4 MB/s eta 0:00:01
   ---------------------------------------  501.8/508.0 kB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 508.0/508.0 kB 2.7 MB/s eta 0:00:00
Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
   ---------------------------------------- 0.0/346.6 kB ? eta -:--:--
   --------------------------------------  337.9/346.6 kB 10.6 MB/s eta 0:00:01
   ---------------------------------------- 346.6/346.6 kB 7.3 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.3 pytz-2024.2 tzdata-2024.2

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: C:\Users\ferna\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

# Pandas

A biblioteca Pandas é uma das ferramentas mais poderosas e amplamente utilizadas para análise e manipulação de dados em Python. Desenvolvida por Wes McKinney, Pandas fornece estruturas de dados flexíveis e eficientes que facilitam o trabalho com dados rotulados e estruturados.

**Por que Usar Pandas?**
- **Versatilidade**: Pandas é adequado para uma ampla gama de tarefas de manipulação de dados, desde análise exploratória até limpeza e transformação de dados.
- **Integração**: Trabalha bem com outras bibliotecas Python, como NumPy, Matplotlib e Scikit-Learn, tornando-o uma escolha natural para workflows da área de dados.
- **Eficiência**: Pandas é otimizado para desempenho e pode lidar com grandes volumes de dados de maneira eficiente.

[Documentação](https://pandas.pydata.org)<br>
[Código](https://github.com/pandas-dev/pandas)

# Series

A Series é o objeto base do Pandas.

In [ ]:
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [ ]:
lista = [1,2,3]

Series do Pandas retorna um formato vertical (Coluna).

Podemos construir `Series` partindo do zero. A forma geral de fazer isso é a seguinte:

```python
pd.Series(data, index = index)
```
`index` é um argumento opcional e `data` pode ser várias coisas

In [ ]:
pd.Series(5, index = [1, 2, 6])

1    5
2    5
6    5
dtype: int64

In [ ]:
# Dicionário
dict_exemplo = {2:'a',
                1:'b',
                3:'c'}
dict_exemplo

{2: 'a', 1: 'b', 3: 'c'}

In [ ]:
pd.Series(dict_exemplo).reset_index(drop=True)#.sort_values('index')#.set_index('index')

0    a
1    b
2    c
dtype: object

In [ ]:
# Criando uma série
s = pd.Series([1, 3, 5, 7, 9])
print(s)

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [ ]:
s[2]

5

In [ ]:
# Selecionando um elemento da série
print(s[2])

5

In [ ]:
s

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [ ]:
# Adicionando um novo elemento à série
s[5] = 11
s

0     1
1     3
2     5
3     7
4     9
5    11
dtype: int64

In [ ]:
# Removendo um elemento da série
s = s.drop(2)
s

0     1
1     3
3     7
4     9
5    11
dtype: int64

## Operações Básicas com Series

In [ ]:
series1 = pd.Series([1,2,3], index=['carne', 'carneiro', 'ovelha'])
series2 = pd.Series([2,3,4], index=['ovo', 'carneiro', 'ovelha'])

In [ ]:
series1

carne       1
carneiro    2
ovelha      3
dtype: int64

In [ ]:
series2

ovo         2
carneiro    3
ovelha      4
dtype: int64

In [ ]:
# Soma
series1 + series2

carne       NaN
carneiro    5.0
ovelha      7.0
ovo         NaN
dtype: float64

In [ ]:
# Divisão
series1/series2
#(series1/series2).round(2)

carne            NaN
carneiro    0.666667
ovelha      0.750000
ovo              NaN
dtype: float64

In [ ]:
# Subtração
series1 - series2

carne       NaN
carneiro   -1.0
ovelha     -1.0
ovo         NaN
dtype: float64

In [ ]:
# Multiplicação
series1*series2

carne        NaN
carneiro     6.0
ovelha      12.0
ovo          NaN
dtype: float64

## Outras possibilidades com Series

In [ ]:
series1

carne       1
carneiro    2
ovelha      3
dtype: int64

In [ ]:
series1.sum()

6

In [ ]:
series1.std()

1.0

In [ ]:
series1.max()

3

In [ ]:
series1.min()

1

In [ ]:
series1.unique()

array([1, 2, 3])

In [ ]:
series1.nunique()

3

In [ ]:
series1

carne       1
carneiro    2
ovelha      3
dtype: int64

In [ ]:
series1 = pd.Series([1,2,3, 1, 3], index=['carne', 'carneiro', 'ovelha', 'boi', 'touro'])
series1

carne       1
carneiro    2
ovelha      3
boi         1
touro       3
dtype: int64

In [ ]:
series1.value_counts()

1    2
3    2
2    1
Name: count, dtype: int64

In [ ]:
series2

ovo         2
carneiro    3
ovelha      4
dtype: int64

In [ ]:
series1

carne       1
carneiro    2
ovelha      3
boi         1
touro       3
dtype: int64

In [ ]:
#isin
series1.isin(series2)

carne       False
carneiro     True
ovelha       True
boi         False
touro        True
dtype: bool

# Exercícios

Dada uma Series com categorias de produtos e suas quantidades vendidas ao longo de uma semana, você deve calcular a frequência de cada categoria e preencher as categorias ausentes com uma quantidade média ajustada. Se uma categoria aparece menos de 3 vezes na semana, substitua suas quantidades por uma média ajustada com base nas categorias mais frequentes.

**Tarefas:**
- Calcule a frequência de cada categoria na Series data.
- Identifique as categorias que aparecem menos de 3 vezes e calcule a média das quantidades das categorias mais frequentes.
- Substitua as quantidades das categorias menos frequentes com a média ajustada calculada.
- Retorne a Series resultante com as categorias e suas quantidades ajustadas.

In [152]:
import numpy as np
index = ['Dia 1', 'Dia 2', 'Dia 3', 'Dia 4', 'Dia 5', 'Dia 6', 'Dia 7']
colunas = ['Carne', 'Frango', 'Peixe', 'Porco', 'Feijão', 'Arroz', 'Macarrão']
data = np.random.randint(0, 2, size=(7, 7))


df_mercado = pd.DataFrame(data=data, index=index, columns=colunas)
df_mercado

       Carne  Frango  Peixe  Porco  Feijão  Arroz  Macarrão
Dia 1      1       0      0      0       1      1         0
Dia 2      0       1      0      0       0      1         0
Dia 3      1       0      1      1       1      1         0
Dia 4      0       1      1      0       0      1         1
Dia 5      0       0      1      1       1      0         0
Dia 6      0       0      1      1       0      0         1
Dia 7      1       1      1      1       1      1         0

In [153]:
df_mercado.sum()

Carne       3
Frango      3
Peixe       5
Porco       4
Feijão      4
Arroz       5
Macarrão    2
dtype: int64

In [165]:
df_mercado['Carne'].mean()

np.float64(0.42857142857142855)

In [173]:
df_mercado['Media'] =df_mercado.mean()
df_mercado

       Carne  Frango  Peixe  Porco  Feijão  Arroz  Macarrão  Media
Dia 1      1       0      0      0       1      1         0    NaN
Dia 2      0       1      0      0       0      1         0    NaN
Dia 3      1       0      1      1       1      1         0    NaN
Dia 4      0       1      1      0       0      1         1    NaN
Dia 5      0       0      1      1       1      0         0    NaN
Dia 6      0       0      1      1       0      0         1    NaN
Dia 7      1       1      1      1       1      1         0    NaN

In [184]:
pd.read_csv('A fazer\#,Comida,Vezes,Dia_da_semana.txt')

FileNotFoundError: [Errno 2] No such file or directory: 'A fazer\\#,Comida,Vezes,Dia_da_semana.txt'